name: Build MSI

on:
  workflow_dispatch: {}
jobs:
  build-msi:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # job-level `if` will skip this job when RUN_WORKFLOW is false

      - name: Set up WiX
        run: |
          choco install wixtoolset --no-progress -y
        shell: powershell

      - name: Prepare environment
        run: |
          # Prefer the version from package.json (authoritative for the build)
          $repoRoot = $env:GITHUB_WORKSPACE
          $pkgPath = Join-Path $repoRoot 'package.json'
          $version = $null
          if (Test-Path $pkgPath) {
            try {
              $pkg = Get-Content -Path $pkgPath -Raw | ConvertFrom-Json
              $version = $pkg.version
            } catch {
              Write-Warning "Failed to parse package.json: $_"
            }
          }
          # Fallback to the git ref name or a default
          if (-not $version) {
            $version = ${{ github.ref_name }}
            if (-not $version) { $version = '1.0.0' }
          }
          Write-Host "Building MSI version: $version"
          # Persist BUILD_VERSION for subsequent steps in this job
          Write-Output ("BUILD_VERSION=$version") | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell

      - name: Prepare dist folder
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File .\scripts\build-dist.ps1 -ProjectRoot $env:GITHUB_WORKSPACE
        shell: pwsh

      - name: Run MSI build
        run: |
          powershell -ExecutionPolicy Bypass -File installer\build-msi.ps1 -Version $env:BUILD_VERSION -SourceDir "$env:GITHUB_WORKSPACE\dist" -OutDir "installer\output"
        shell: powershell

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: creo-msi
          path: installer\output\*.msi
